import test from "node:test";
import assert from "node:assert/strict";
import { FourSovereignFabric, FOUR_SOVEREIGNS } from "../src/system/FourSovereignFabric";

const fabric = new FourSovereignFabric("NATIONAL_SECURITY");

test("fabric defines four specialized sovereign roles", () => { assert.equal(fabric.definitions().length, 4); assert.equal(FOUR_SOVEREIGNS.SOVEREIGN_1.role, "STITCHBRICK_INTEGRITY"); assert.equal(FOUR_SOVEREIGNS.SOVEREIGN_2.role, "IRONLINK3_TRANSPORT"); assert.equal(FOUR_SOVEREIGNS.SOVEREIGN_3.role, "WATCHDOG_OVERSEER"); assert.equal(FOUR_SOVEREIGNS.SOVEREIGN_4.role, "QUBIX_NODE_BRIGADE"); });
test("IronLink 3 transports but cannot certify or repair", () => { assert.equal(fabric.authorizeAction("SOVEREIGN_2", "TRANSPORT").accepted, true); assert.equal(fabric.authorizeAction("SOVEREIGN_2", "CERTIFY").accepted, false); assert.equal(fabric.authorizeAction("SOVEREIGN_2", "REPAIR_CANDIDATE").accepted, false); });
test("Watchdog sees and escalates but cannot transport repair or certify", () => { assert.equal(fabric.authorizeAction("SOVEREIGN_3", "CORRELATE").accepted, true); assert.equal(fabric.authorizeAction("SOVEREIGN_3", "ALERT").accepted, true); assert.equal(fabric.authorizeAction("SOVEREIGN_3", "TRANSPORT").accepted, false); assert.equal(fabric.authorizeAction("SOVEREIGN_3", "CERTIFY").accepted, false); assert.equal(fabric.authorizeAction("SOVEREIGN_3", "REPAIR_CANDIDATE").accepted, false); });
test("Node Brigade reports upward only to main Sovereign 1", () => { const report = fabric.createReport("SOVEREIGN_4", "SOVEREIGN_1", "REVERIFY", ["evidence:1"], "constitution-v1", "r1"); assert.equal(report.trusted, false); assert.equal(report.mayTouchSpine, false); assert.equal(report.requiresTransportGate, true); assert.throws(() => fabric.createReport("SOVEREIGN_4", "SOVEREIGN_3", "REVERIFY", ["evidence:1"], "constitution-v1")); });
test("only IronLink 3 may carry a governed cross-sovereign report", () => { const report = fabric.createReport("SOVEREIGN_4", "SOVEREIGN_1", "VERIFY", ["proof:a"], "constitution-v1", "r2"); assert.equal(fabric.authorizeTransport(report, "SOVEREIGN_2").accepted, true); assert.equal(fabric.authorizeTransport(report, "SOVEREIGN_3").accepted, false); });
test("Sovereign 1 coordinates integrity but does not inherit transport authority", () => { assert.equal(fabric.authorizeAction("SOVEREIGN_1", "PURIFY").accepted, true); assert.equal(fabric.authorizeAction("SOVEREIGN_1", "COORDINATE_RECOVERY").accepted, true); assert.equal(fabric.authorizeAction("SOVEREIGN_1", "TRANSPORT").accepted, false); });
