/**
 * EvidenceBundle — Phase 20 formal evidence generation.
 *
 * Every formal verification run generates a unique run ID.
 * The bundle records:
 *   - run ID (unique per run)
 *   - start/end timestamps
 *   - environment (node version, platform, arch, package version)
 *   - test results summary
 *   - ledger anchor at time of evidence capture
 *   - integrity assertion: SILENT_TRUST_ESCAPES
 *
 * Machine-readable output: JSON.
 * Human-readable summary: Markdown.
 */
import { createHash, randomBytes } from "node:crypto";
import { hashOf } from "../utils/hash";

export interface EnvironmentInfo {
  readonly nodeVersion: string;
  readonly platform: string;
  readonly arch: string;
  readonly packageVersion: string;
  readonly capturedAt: string;
}

export interface TestResultSummary {
  readonly total: number;
  readonly passed: number;
  readonly failed: number;
  readonly skipped: number;
  readonly silentTrustEscapes: number;
}

export interface EvidenceRecord {
  readonly runId: string;
  readonly startedAt: string;
  readonly completedAt: string;
  readonly environment: EnvironmentInfo;
  readonly tests: TestResultSummary;
  readonly bundleHash: string;
}

export interface EvidenceBundleOptions {
  readonly packageVersion?: string;
  readonly clock?: () => string;
}

export class EvidenceBundle {
  private readonly startedAt: string;
  private readonly runId: string;
  private readonly clock: () => string;
  private readonly packageVersion: string;

  constructor(options: EvidenceBundleOptions = {}) {
    this.clock = options.clock ?? (() => new Date().toISOString());
    this.packageVersion = options.packageVersion ?? "unknown";
    this.startedAt = this.clock();
    // Run ID: timestamp prefix + 8 bytes of entropy for uniqueness
    const entropy = randomBytes(8).toString("hex");
    const ts = this.startedAt.replace(/[^0-9T]/g, "").slice(0, 15);
    this.runId = `run_${ts}_${entropy}`;
  }

  get id(): string {
    return this.runId;
  }

  /**
   * Finalise the bundle with test results.
   * Returns a machine-readable EvidenceRecord and a human-readable Markdown string.
   */
  finalize(tests: TestResultSummary): { record: EvidenceRecord; markdown: string } {
    const completedAt = this.clock();
    const environment: EnvironmentInfo = {
      nodeVersion: process.version,
      platform: process.platform,
      arch: process.arch,
      packageVersion: this.packageVersion,
      capturedAt: completedAt,
    };

    // Bundle hash covers all fields except itself
    const bundleContent = {
      runId: this.runId,
      startedAt: this.startedAt,
      completedAt,
      environment,
      tests,
    };
    const bundleHash = "sha256:" + createHash("sha256")
      .update(JSON.stringify(bundleContent))
      .digest("hex");

    const record: EvidenceRecord = Object.freeze({
      ...bundleContent,
      bundleHash,
    });

    const markdown = this.toMarkdown(record);
    return { record, markdown };
  }

  /** Hash a given object for use as an evidence anchor. */
  static hashContent(value: unknown): string {
    return hashOf(value);
  }

  private toMarkdown(r: EvidenceRecord): string {
    const status = r.tests.failed === 0 && r.tests.silentTrustEscapes === 0 ? "✅ PASSED" : "❌ FAILED";
    return [
      `# SB688 Verification Evidence`,
      ``,
      `**Run ID:** \`${r.runId}\``,
      `**Status:** ${status}`,
      `**Started:** ${r.startedAt}`,
      `**Completed:** ${r.completedAt}`,
      ``,
      `## Environment`,
      `| Field | Value |`,
      `|---|---|`,
      `| Node | ${r.environment.nodeVersion} |`,
      `| Platform | ${r.environment.platform} |`,
      `| Arch | ${r.environment.arch} |`,
      `| Package | ${r.environment.packageVersion} |`,
      ``,
      `## Test Results`,
      `| Metric | Value |`,
      `|---|---|`,
      `| Total | ${r.tests.total} |`,
      `| Passed | ${r.tests.passed} |`,
      `| Failed | ${r.tests.failed} |`,
      `| Skipped | ${r.tests.skipped} |`,
      `| **Silent Trust Escapes** | **${r.tests.silentTrustEscapes}** |`,
      ``,
      `## Integrity`,
      `**Bundle Hash:** \`${r.bundleHash}\``,
      ``,
      r.tests.silentTrustEscapes > 0
        ? `> ⚠️ WARNING: ${r.tests.silentTrustEscapes} silent trust escape(s) detected. The invariant SILENT_TRUST_ESCAPES=0 has been VIOLATED.`
        : `> ✅ SILENT_TRUST_ESCAPES = 0 — invariant satisfied.`,
      ``,
      `---`,
      `*Generated by EvidenceBundle. Do not edit manually.*`,
    ].join("\n");
  }
}
